//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Account_id { get; set; }
        public Nullable<int> Accountant_id { get; set; }
        public Nullable<int> Insurance_company_id { get; set; }
        public string Number { get; set; }
    
        public virtual Accountants Accountants { get; set; }
        public virtual Insurance_companies Insurance_companies { get; set; }
    }
}
