//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analyzers_data
    {
        public int Data_id { get; set; }
        public Nullable<System.DateTime> Entrance_date_time { get; set; }
        public Nullable<int> Complete_time_in_sec { get; set; }
        public Nullable<int> Analyzer_id { get; set; }
    
        public virtual Analyzers Analyzers { get; set; }
    }
}
