//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int History_id { get; set; }
        public int User_id { get; set; }
        public Nullable<System.DateTime> Enter_date_time { get; set; }
        public Nullable<System.DateTime> Logout_date_time { get; set; }
        public Nullable<bool> Is_succes { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
