//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_id { get; set; }
        public System.DateTime Create_date { get; set; }
        public int Complete_time_in_days { get; set; }
        public int Patient_id { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
